version: "3.1"

services: 
    iosAPI:
        image: iosapi
        restart: always
        ports: 
            - "8081:8080"
        depends_on: 
            - redis
            - mongo

    redis:
        image: redis:latest
        restart: always
        volumes: 
            - ./redis-data:/data
        environment: 
            - TZ=Asia/Shanghai

    mongo:
        image: mongo:latest
        restart: always
        volumes: 
            - ./mongo-data:/data/db

networks: 
    default:
        external: 
            name: iosAPI